-- Script simplifié pour créer la table realtime_notifications
-- Exécuter dans l'éditeur SQL de Supabase

-- 1. Créer la table
CREATE TABLE IF NOT EXISTS public.realtime_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id bigint NOT NULL,
  to_user_id bigint NOT NULL,
  type_notification character varying NOT NULL CHECK (type_notification IN (
    'call_patient',
    'patient_called',
    'consultation_started',
    'consultation_finished'
  )),
  patient_id bigint,
  waiting_queue_id bigint,
  message text NOT NULL,
  data jsonb,
  status character varying DEFAULT 'pending' CHECK (status IN ('pending', 'read', 'confirmed')),
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone
);

-- 2. Ajouter les clés étrangères
ALTER TABLE public.realtime_notifications 
ADD CONSTRAINT IF NOT EXISTS fk_realtime_notifications_from_user 
FOREIGN KEY (from_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.realtime_notifications 
ADD CONSTRAINT IF NOT EXISTS fk_realtime_notifications_to_user 
FOREIGN KEY (to_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.realtime_notifications 
ADD CONSTRAINT IF NOT EXISTS fk_realtime_notifications_patient 
FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;

ALTER TABLE public.realtime_notifications 
ADD CONSTRAINT IF NOT EXISTS fk_realtime_notifications_waiting_queue 
FOREIGN KEY (waiting_queue_id) REFERENCES public.waiting_queue(id) ON DELETE CASCADE;

-- 3. Créer les index
CREATE INDEX IF NOT EXISTS idx_realtime_notifications_to_user ON public.realtime_notifications(to_user_id, status);
CREATE INDEX IF NOT EXISTS idx_realtime_notifications_type ON public.realtime_notifications(type_notification);
CREATE INDEX IF NOT EXISTS idx_realtime_notifications_waiting_queue ON public.realtime_notifications(waiting_queue_id);

-- 4. Vérifier que la table a été créée
SELECT 
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns 
WHERE table_name = 'realtime_notifications' 
    AND table_schema = 'public'
ORDER BY ordinal_position;
