-- Créer une table pour les notifications temps réel entre médecin et secrétaire
CREATE TABLE IF NOT EXISTS public.realtime_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  to_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type_notification character varying NOT NULL CHECK (type_notification IN (
    'call_patient',           -- Médecin demande d'appeler un patient
    'patient_called',         -- Secrétaire confirme avoir appelé
    'consultation_started',   -- Consultation commencée
    'consultation_finished'   -- Consultation terminée
  )),
  patient_id bigint REFERENCES public.patients(id) ON DELETE CASCADE,
  waiting_queue_id bigint REFERENCES public.waiting_queue(id) ON DELETE CASCADE,
  message text NOT NULL,
  data jsonb, -- Données supplémentaires (compteur, etc.)
  status character varying DEFAULT 'pending' CHECK (status IN ('pending', 'read', 'confirmed')),
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone
);

-- Index pour les performances
CREATE INDEX IF NOT EXISTS idx_realtime_notifications_to_user ON public.realtime_notifications(to_user_id, status);
CREATE INDEX IF NOT EXISTS idx_realtime_notifications_type ON public.realtime_notifications(type_notification);
CREATE INDEX IF NOT EXISTS idx_realtime_notifications_waiting_queue ON public.realtime_notifications(waiting_queue_id);

-- RLS (Row Level Security)
ALTER TABLE public.realtime_notifications ENABLE ROW LEVEL SECURITY;

-- Politique : Les utilisateurs peuvent voir leurs notifications
CREATE POLICY "Users can view their notifications" ON public.realtime_notifications
  FOR SELECT USING (auth.uid()::text = (SELECT auth_id FROM public.users WHERE id = to_user_id));

-- Politique : Les utilisateurs peuvent créer des notifications
CREATE POLICY "Users can create notifications" ON public.realtime_notifications
  FOR INSERT WITH CHECK (auth.uid()::text = (SELECT auth_id FROM public.users WHERE id = from_user_id));

-- Politique : Les utilisateurs peuvent mettre à jour leurs notifications
CREATE POLICY "Users can update their notifications" ON public.realtime_notifications
  FOR UPDATE USING (auth.uid()::text = (SELECT auth_id FROM public.users WHERE id = to_user_id));
