-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.actes (
  id bigint NOT NULL DEFAULT nextval('actes_id_seq'::regclass),
  consultation_id bigint,
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  date_acte date NOT NULL,
  type_acte character varying NOT NULL,
  description text,
  montant numeric DEFAULT 0,
  statut character varying DEFAULT 'en_cours'::character varying CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'annule'::character varying]::text[])),
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT actes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_actes_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_actes_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_actes_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id),
  CONSTRAINT actes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT actes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.actes_consultation (
  id integer NOT NULL DEFAULT nextval('actes_consultation_id_seq'::regclass),
  consultation_id bigint,
  type_acte_id bigint,
  quantite integer DEFAULT 1,
  tarif_unitaire numeric NOT NULL,
  montant_total numeric DEFAULT ((quantite)::numeric * tarif_unitaire),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT actes_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT fk_actes_consultation_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_actes_consultation_type_acte FOREIGN KEY (type_acte_id) REFERENCES public.types_actes(id),
  CONSTRAINT fk_actes_consultation_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_actes_consultation_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.analyses_labo_prescrites (
  id integer NOT NULL DEFAULT nextval('analyses_labo_prescrites_id_seq'::regclass),
  consultation_id bigint,
  patient_id bigint,
  type_analyse character varying NOT NULL,
  description text,
  urgence boolean DEFAULT false,
  date_prescription date DEFAULT CURRENT_DATE,
  date_prelevement date,
  date_resultat date,
  statut character varying DEFAULT 'prescrit'::character varying CHECK (statut::text = ANY (ARRAY['prescrit'::character varying, 'preleve'::character varying, 'en_cours'::character varying, 'termine'::character varying, 'annule'::character varying]::text[])),
  resultat text,
  valeurs_normales text,
  interpretation text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT analyses_labo_prescrites_pkey PRIMARY KEY (id),
  CONSTRAINT fk_analyses_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_analyses_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_analyses_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_analyses_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.analyses_tendances (
  id bigint NOT NULL DEFAULT nextval('analyses_tendances_id_seq'::regclass),
  nom_analyse character varying NOT NULL,
  type_metrique character varying NOT NULL CHECK (type_metrique::text = ANY (ARRAY['consultations'::character varying, 'revenus'::character varying, 'patients'::character varying, 'actes'::character varying, 'duree'::character varying]::text[])),
  periode_analyse character varying NOT NULL CHECK (periode_analyse::text = ANY (ARRAY['jour'::character varying, 'semaine'::character varying, 'mois'::character varying, 'trimestre'::character varying, 'annee'::character varying]::text[])),
  date_debut_analyse date NOT NULL,
  date_fin_analyse date NOT NULL,
  donnees_tendance jsonb NOT NULL,
  coefficient_tendance numeric,
  r_squared numeric,
  prediction_prochaine_periode numeric,
  intervalle_confiance jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analyses_tendances_pkey PRIMARY KEY (id)
);
CREATE TABLE public.annuaire_actes_tarifs (
  id bigint NOT NULL DEFAULT nextval('annuaire_actes_tarifs_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  code_ccam character varying,
  tarif_base numeric DEFAULT 0,
  tarif_secu numeric DEFAULT 0,
  tarif_mutuelle numeric DEFAULT 0,
  categorie character varying,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT annuaire_actes_tarifs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.antecedents (
  id bigint NOT NULL DEFAULT nextval('antecedents_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  categorie character varying DEFAULT 'generale'::character varying,
  code_cim character varying,
  niveau_gravite character varying DEFAULT 'leger'::character varying CHECK (niveau_gravite::text = ANY (ARRAY['leger'::character varying, 'modere'::character varying, 'grave'::character varying, 'critique'::character varying]::text[])),
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT antecedents_pkey PRIMARY KEY (id),
  CONSTRAINT fk_antecedents_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_antecedents_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.antecedents_patients (
  id bigint NOT NULL DEFAULT nextval('antecedents_patients_id_seq'::regclass),
  patient_id bigint NOT NULL,
  antecedent_id bigint NOT NULL,
  consultation_id bigint,
  date_decouverte date,
  commentaires text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT antecedents_patients_pkey PRIMARY KEY (id),
  CONSTRAINT antecedents_patients_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT antecedents_patients_antecedent_id_fkey FOREIGN KEY (antecedent_id) REFERENCES public.antecedents(id),
  CONSTRAINT antecedents_patients_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.appareils (
  id bigint NOT NULL DEFAULT nextval('appareils_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  specialite_id bigint,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT appareils_pkey PRIMARY KEY (id),
  CONSTRAINT fk_appareils_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_appareils_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_appareils_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.appointments (
  id bigint NOT NULL DEFAULT nextval('appointments_id_seq'::regclass),
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  date_heure timestamp with time zone NOT NULL,
  motif character varying,
  statut character varying DEFAULT 'confirme'::character varying CHECK (statut::text = ANY (ARRAY['confirme'::character varying, 'en_attente'::character varying, 'annule'::character varying]::text[])),
  duree integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  priorite character varying DEFAULT 'normale'::character varying CHECK (priorite::text = ANY (ARRAY['normale'::character varying::text, 'urgente'::character varying::text, 'tres_urgente'::character varying::text])),
  couleur character varying DEFAULT '#3b82f6'::character varying,
  heure_fin timestamp with time zone,
  type_rdv character varying DEFAULT 'consultation'::character varying CHECK (type_rdv::text = ANY (ARRAY['consultation'::character varying, 'suivi'::character varying, 'urgence'::character varying, 'preventif'::character varying]::text[])),
  notes text,
  rappel_envoye boolean DEFAULT false,
  rappel_veille_envoye boolean DEFAULT false,
  motif_detaille text,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT appointments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_appointments_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.apprentissage_continu (
  id bigint NOT NULL DEFAULT nextval('apprentissage_continu_id_seq'::regclass),
  modele_id bigint,
  type_action character varying NOT NULL CHECK (type_action::text = ANY (ARRAY['entrainement'::character varying, 'evaluation'::character varying, 'optimisation'::character varying]::text[])),
  donnees_utilisees jsonb,
  parametres_entrainement jsonb,
  resultats jsonb,
  amelioration_performance numeric,
  date_debut timestamp with time zone DEFAULT now(),
  date_fin timestamp with time zone,
  statut character varying DEFAULT 'en_cours'::character varying CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'erreur'::character varying]::text[])),
  CONSTRAINT apprentissage_continu_pkey PRIMARY KEY (id),
  CONSTRAINT apprentissage_continu_modele_id_fkey FOREIGN KEY (modele_id) REFERENCES public.modeles_ia(id)
);
CREATE TABLE public.archives (
  id bigint NOT NULL DEFAULT nextval('archives_id_seq'::regclass),
  patient_id bigint NOT NULL,
  famille_archive_id bigint NOT NULL,
  type_archive_id bigint NOT NULL,
  titre character varying NOT NULL,
  description text,
  date_archivage date NOT NULL,
  statut character varying DEFAULT 'actif'::character varying CHECK (statut::text = ANY (ARRAY['actif'::character varying, 'inactif'::character varying, 'supprime'::character varying]::text[])),
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT archives_pkey PRIMARY KEY (id),
  CONSTRAINT fk_archives_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_archives_famille FOREIGN KEY (famille_archive_id) REFERENCES public.familles_archives(id),
  CONSTRAINT fk_archives_type FOREIGN KEY (type_archive_id) REFERENCES public.types_archives(id),
  CONSTRAINT archives_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT archives_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.assurances (
  id bigint NOT NULL DEFAULT nextval('assurances_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  type_assurance character varying DEFAULT 'mutuelle'::character varying CHECK (type_assurance::text = ANY (ARRAY['mutuelle'::character varying, 'securite_sociale'::character varying, 'privee'::character varying, 'autre'::character varying]::text[])),
  taux_remboursement numeric,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT assurances_pkey PRIMARY KEY (id),
  CONSTRAINT fk_assurances_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_assurances_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.autres_signes_physiques (
  id bigint NOT NULL DEFAULT nextval('autres_signes_physiques_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  description text NOT NULL,
  categorie character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT autres_signes_physiques_pkey PRIMARY KEY (id),
  CONSTRAINT autres_signes_physiques_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.canal_provenance (
  id bigint NOT NULL DEFAULT nextval('canal_provenance_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT canal_provenance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.certificats_medicaux (
  id bigint NOT NULL DEFAULT nextval('certificats_medicaux_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  type_certificat_id bigint NOT NULL,
  duree_jours integer,
  motif text,
  restrictions text,
  date_debut date DEFAULT CURRENT_DATE,
  date_fin date,
  statut character varying DEFAULT 'actif'::character varying CHECK (statut::text = ANY (ARRAY['actif'::character varying, 'expire'::character varying, 'annule'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_id bigint,
  medecin_id bigint,
  CONSTRAINT certificats_medicaux_pkey PRIMARY KEY (id),
  CONSTRAINT certificats_medicaux_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT certificats_medicaux_medecin_id_fkey FOREIGN KEY (medecin_id) REFERENCES public.users(id),
  CONSTRAINT certificats_medicaux_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT certificats_medicaux_type_certificat_id_fkey FOREIGN KEY (type_certificat_id) REFERENCES public.types_certificats(id)
);
CREATE TABLE public.constantes (
  id bigint NOT NULL DEFAULT nextval('constantes_id_seq'::regclass),
  nom character varying NOT NULL UNIQUE,
  description text,
  unite character varying,
  valeur_min numeric,
  valeur_max numeric,
  valeur_normale_min numeric,
  valeur_normale_max numeric,
  categorie character varying DEFAULT 'generale'::character varying,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT constantes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_constantes_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_constantes_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.constantes_consultation (
  id bigint NOT NULL DEFAULT nextval('constantes_consultation_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  constante_id bigint NOT NULL,
  valeur_mesuree numeric NOT NULL,
  unite character varying,
  commentaires text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT constantes_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT constantes_consultation_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT constantes_consultation_constante_id_fkey FOREIGN KEY (constante_id) REFERENCES public.constantes(id)
);
CREATE TABLE public.constats_appareils (
  id bigint NOT NULL DEFAULT nextval('constats_appareils_id_seq'::regclass),
  appareil_id bigint NOT NULL,
  nom character varying NOT NULL,
  description text,
  type_constat character varying DEFAULT 'normal'::character varying CHECK (type_constat::text = ANY (ARRAY['normal'::character varying, 'anormal'::character varying, 'pathologique'::character varying]::text[])),
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT constats_appareils_pkey PRIMARY KEY (id),
  CONSTRAINT fk_constats_appareil FOREIGN KEY (appareil_id) REFERENCES public.appareils(id),
  CONSTRAINT fk_constats_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_constats_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.consultations (
  id bigint NOT NULL DEFAULT nextval('consultations_id_seq'::regclass),
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  date_consultation date NOT NULL,
  motif character varying,
  diagnostic text,
  traitement text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  duree_consultation integer DEFAULT 0,
  niveau_urgence character varying DEFAULT 'normale'::character varying CHECK (niveau_urgence::text = ANY (ARRAY['normale'::character varying, 'urgente'::character varying, 'tres_urgente'::character varying]::text[])),
  type_consultation character varying DEFAULT 'standard'::character varying CHECK (type_consultation::text = ANY (ARRAY['standard'::character varying, 'suivi'::character varying, 'urgence'::character varying, 'preventive'::character varying]::text[])),
  notes_confidentielles text,
  plan_suivi text,
  prochaine_consultation date,
  statut character varying DEFAULT 'en_cours'::character varying CHECK (statut::text = ANY (ARRAY['en_cours'::character varying::text, 'terminee'::character varying::text, 'annulee'::character varying::text])),
  appointment_id bigint,
  motif_consultation text,
  notes_generales text,
  CONSTRAINT consultations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_consultations_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT fk_consultations_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_consultations_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.correlations_detectees (
  id bigint NOT NULL DEFAULT nextval('correlations_detectees_id_seq'::regclass),
  regle_id bigint,
  metrique_1 character varying NOT NULL,
  metrique_2 character varying NOT NULL,
  coefficient_correlation numeric NOT NULL,
  significativite numeric,
  periode_analyse jsonb,
  interpretation text,
  date_detection timestamp with time zone DEFAULT now(),
  CONSTRAINT correlations_detectees_pkey PRIMARY KEY (id),
  CONSTRAINT correlations_detectees_regle_id_fkey FOREIGN KEY (regle_id) REFERENCES public.regles_alertes_avancees(id)
);
CREATE TABLE public.diagnostics (
  id bigint NOT NULL DEFAULT nextval('diagnostics_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  code_cim character varying,
  specialite_id bigint,
  niveau_gravite character varying DEFAULT 'leger'::character varying CHECK (niveau_gravite::text = ANY (ARRAY['leger'::character varying, 'modere'::character varying, 'grave'::character varying, 'critique'::character varying]::text[])),
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT diagnostics_pkey PRIMARY KEY (id),
  CONSTRAINT fk_diagnostics_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_diagnostics_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_diagnostics_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.diagnostics_consultation (
  id bigint NOT NULL DEFAULT nextval('diagnostics_consultation_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  diagnostic_id bigint NOT NULL,
  commentaires text,
  certitude character varying DEFAULT 'probable'::character varying CHECK (certitude::text = ANY (ARRAY['certain'::character varying, 'probable'::character varying, 'possible'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diagnostics_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT diagnostics_consultation_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT diagnostics_consultation_diagnostic_id_fkey FOREIGN KEY (diagnostic_id) REFERENCES public.diagnostics(id)
);
CREATE TABLE public.disponibilites_medecins (
  id bigint NOT NULL DEFAULT nextval('disponibilites_medecins_id_seq'::regclass),
  medecin_id bigint NOT NULL,
  date_disponibilite date NOT NULL,
  heure_debut time without time zone NOT NULL,
  heure_fin time without time zone NOT NULL,
  statut character varying DEFAULT 'disponible'::character varying CHECK (statut::text = ANY (ARRAY['disponible'::character varying, 'indisponible'::character varying, 'pause'::character varying, 'conges'::character varying]::text[])),
  motif_indisponibilite text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT disponibilites_medecins_pkey PRIMARY KEY (id),
  CONSTRAINT fk_disponibilites_medecins_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.divers_instructions (
  id bigint NOT NULL DEFAULT nextval('divers_instructions_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  type_instruction character varying NOT NULL DEFAULT 'general'::character varying,
  titre character varying NOT NULL,
  description text NOT NULL,
  priorite character varying DEFAULT 'normale'::character varying CHECK (priorite::text = ANY (ARRAY['basse'::character varying, 'normale'::character varying, 'haute'::character varying, 'urgente'::character varying]::text[])),
  statut character varying DEFAULT 'en_attente'::character varying CHECK (statut::text = ANY (ARRAY['en_attente'::character varying, 'en_cours'::character varying, 'terminee'::character varying, 'annulee'::character varying]::text[])),
  date_creation timestamp with time zone DEFAULT now(),
  date_modification timestamp with time zone DEFAULT now(),
  date_execution timestamp with time zone,
  notes_execution text,
  created_by bigint,
  updated_by bigint,
  CONSTRAINT divers_instructions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_divers_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_divers_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.documents_patients (
  id bigint NOT NULL DEFAULT nextval('documents_patients_id_seq'::regclass),
  patient_id bigint NOT NULL,
  type_document character varying NOT NULL CHECK (type_document::text = ANY (ARRAY['analyse'::character varying, 'imagerie'::character varying, 'prescription'::character varying, 'certificat'::character varying, 'autre'::character varying]::text[])),
  nom_fichier character varying NOT NULL,
  url_fichier character varying NOT NULL,
  taille_fichier bigint,
  format_fichier character varying,
  description text,
  date_scan timestamp with time zone DEFAULT now(),
  scanned_by bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  date_document date,
  statut_validation character varying DEFAULT 'valide'::character varying CHECK (statut_validation::text = ANY (ARRAY['en_attente'::character varying, 'valide'::character varying, 'rejete'::character varying, 'archive'::character varying]::text[])),
  apercu_url character varying,
  apercu_genere boolean DEFAULT false,
  hash_fichier character varying,
  consultation_id bigint,
  CONSTRAINT documents_patients_pkey PRIMARY KEY (id),
  CONSTRAINT fk_documents_patients_consultation_id FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_documents_patients_scanned_by FOREIGN KEY (scanned_by) REFERENCES public.users(id),
  CONSTRAINT fk_documents_patients_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.elements_synthese (
  id bigint NOT NULL DEFAULT nextval('elements_synthese_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  categorie character varying DEFAULT 'generale'::character varying,
  type_element character varying DEFAULT 'observation'::character varying CHECK (type_element::text = ANY (ARRAY['observation'::character varying, 'conclusion'::character varying, 'recommandation'::character varying, 'prescription'::character varying]::text[])),
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT elements_synthese_pkey PRIMARY KEY (id),
  CONSTRAINT fk_elements_synthese_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_elements_synthese_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.employeurs (
  id bigint NOT NULL DEFAULT nextval('employeurs_id_seq'::regclass),
  nom character varying NOT NULL,
  adresse text,
  telephone character varying,
  email character varying,
  siret character varying,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employeurs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.examens_appareils (
  id bigint NOT NULL DEFAULT nextval('examens_appareils_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  appareil_id bigint NOT NULL,
  resultat_examen text,
  anomalies_detectees text,
  recommandations text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT examens_appareils_pkey PRIMARY KEY (id),
  CONSTRAINT examens_appareils_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT examens_appareils_appareil_id_fkey FOREIGN KEY (appareil_id) REFERENCES public.appareils(id)
);
CREATE TABLE public.examens_diagnostic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nom character varying NOT NULL UNIQUE,
  description text,
  preparation text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT examens_diagnostic_pkey PRIMARY KEY (id)
);
CREATE TABLE public.examens_medicaux (
  id bigint NOT NULL DEFAULT nextval('examens_medicaux_id_seq'::regclass),
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  consultation_id bigint,
  type_examen character varying NOT NULL,
  description text,
  resultat text,
  date_examen date NOT NULL,
  statut character varying DEFAULT 'en_cours'::character varying CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'annule'::character varying]::text[])),
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT examens_medicaux_pkey PRIMARY KEY (id),
  CONSTRAINT fk_examens_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_examens_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id),
  CONSTRAINT fk_examens_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT examens_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT examens_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.examens_prescrits (
  id integer NOT NULL DEFAULT nextval('examens_prescrits_id_seq'::regclass),
  consultation_id bigint,
  patient_id bigint,
  type_examen character varying NOT NULL,
  description text,
  urgence boolean DEFAULT false,
  date_prescription date DEFAULT CURRENT_DATE,
  date_realisation date,
  statut character varying DEFAULT 'prescrit'::character varying CHECK (statut::text = ANY (ARRAY['prescrit'::character varying, 'en_cours'::character varying, 'termine'::character varying, 'annule'::character varying]::text[])),
  resultat text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT examens_prescrits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exports_programmes (
  id bigint NOT NULL DEFAULT nextval('exports_programmes_id_seq'::regclass),
  nom_export character varying NOT NULL,
  template_id bigint,
  frequence character varying NOT NULL CHECK (frequence::text = ANY (ARRAY['unique'::character varying, 'quotidien'::character varying, 'hebdomadaire'::character varying, 'mensuel'::character varying]::text[])),
  parametres_export jsonb,
  destinataires jsonb,
  derniere_execution timestamp with time zone,
  prochaine_execution timestamp with time zone,
  statut character varying DEFAULT 'actif'::character varying CHECK (statut::text = ANY (ARRAY['actif'::character varying, 'inactif'::character varying, 'pause'::character varying]::text[])),
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exports_programmes_pkey PRIMARY KEY (id),
  CONSTRAINT exports_programmes_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates_export(id),
  CONSTRAINT exports_programmes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.factures (
  id integer NOT NULL DEFAULT nextval('factures_id_seq1'::regclass),
  consultation_id bigint,
  patient_id bigint,
  numero_facture character varying NOT NULL UNIQUE,
  date_facture date DEFAULT CURRENT_DATE,
  montant_ht numeric DEFAULT 0,
  tva numeric DEFAULT 0,
  montant_ttc numeric DEFAULT 0,
  montant_paye numeric DEFAULT 0,
  montant_restant numeric DEFAULT (montant_ttc - montant_paye),
  statut_paiement character varying DEFAULT 'en_attente'::character varying CHECK (statut_paiement::text = ANY (ARRAY['en_attente'::character varying, 'partiel'::character varying, 'paye'::character varying, 'impaye'::character varying]::text[])),
  mode_paiement character varying,
  assurance_id bigint,
  numero_carte character varying,
  emetteur_monnaie_electronique character varying,
  date_paiement timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT factures_pkey PRIMARY KEY (id),
  CONSTRAINT fk_factures_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_factures_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_factures_assurance FOREIGN KEY (assurance_id) REFERENCES public.assurances(id),
  CONSTRAINT fk_factures_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_factures_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.factures_old (
  id bigint NOT NULL DEFAULT nextval('factures_id_seq'::regclass),
  acte_id bigint,
  patient_id bigint NOT NULL,
  numero_facture character varying NOT NULL UNIQUE,
  montant_ht numeric NOT NULL,
  tva numeric DEFAULT 0,
  montant_ttc numeric NOT NULL,
  mode_reglement character varying,
  statut_paiement character varying DEFAULT 'en_attente'::character varying CHECK (statut_paiement::text = ANY (ARRAY['en_attente'::character varying, 'paye'::character varying, 'impaye'::character varying, 'partiel'::character varying]::text[])),
  date_echeance date,
  notes text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT factures_old_pkey PRIMARY KEY (id),
  CONSTRAINT fk_factures_acte FOREIGN KEY (acte_id) REFERENCES public.actes(id),
  CONSTRAINT fk_factures_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT factures_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT factures_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.familles_archives (
  id bigint NOT NULL DEFAULT nextval('familles_archives_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT familles_archives_pkey PRIMARY KEY (id)
);
CREATE TABLE public.favoris_medecins (
  id integer NOT NULL DEFAULT nextval('favoris_medecins_id_seq'::regclass),
  medecin_id bigint,
  type_favori character varying NOT NULL,
  element_id integer NOT NULL,
  ordre integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favoris_medecins_pkey PRIMARY KEY (id),
  CONSTRAINT favoris_medecins_medecin_id_fkey FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.filtres_globaux (
  id bigint NOT NULL DEFAULT nextval('filtres_globaux_id_seq'::regclass),
  nom_filtre character varying NOT NULL,
  description text,
  type_filtre character varying NOT NULL CHECK (type_filtre::text = ANY (ARRAY['date'::character varying, 'utilisateur'::character varying, 'specialite'::character varying, 'statut'::character varying, 'personnalise'::character varying]::text[])),
  configuration_filtre jsonb NOT NULL,
  valeurs_defaut jsonb,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT filtres_globaux_pkey PRIMARY KEY (id),
  CONSTRAINT filtres_globaux_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.historique_alertes (
  id bigint NOT NULL DEFAULT nextval('historique_alertes_id_seq'::regclass),
  regle_id bigint,
  type_alerte character varying NOT NULL,
  message text NOT NULL,
  donnees_contexte jsonb,
  statut character varying DEFAULT 'nouvelle'::character varying CHECK (statut::text = ANY (ARRAY['nouvelle'::character varying, 'lue'::character varying, 'traitee'::character varying, 'ignoree'::character varying]::text[])),
  priorite character varying DEFAULT 'normale'::character varying,
  date_declenchement timestamp with time zone DEFAULT now(),
  date_traitement timestamp with time zone,
  traite_par bigint,
  notes_traitement text,
  CONSTRAINT historique_alertes_pkey PRIMARY KEY (id),
  CONSTRAINT historique_alertes_regle_id_fkey FOREIGN KEY (regle_id) REFERENCES public.regles_alertes(id),
  CONSTRAINT historique_alertes_traite_par_fkey FOREIGN KEY (traite_par) REFERENCES public.users(id)
);
CREATE TABLE public.historique_consultations (
  id integer NOT NULL DEFAULT nextval('historique_consultations_id_seq'::regclass),
  consultation_id integer,
  medecin_id bigint,
  action character varying NOT NULL,
  section_modifiee character varying,
  anciennes_valeurs jsonb,
  nouvelles_valeurs jsonb,
  commentaire text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historique_consultations_pkey PRIMARY KEY (id),
  CONSTRAINT historique_consultations_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT historique_consultations_medecin_id_fkey FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.historique_exports (
  id bigint NOT NULL DEFAULT nextval('historique_exports_id_seq'::regclass),
  export_programme_id bigint,
  template_id bigint,
  date_execution timestamp with time zone DEFAULT now(),
  statut character varying NOT NULL CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'erreur'::character varying]::text[])),
  url_fichier character varying,
  taille_fichier bigint,
  duree_generation integer,
  nombre_lignes integer,
  message_erreur text,
  CONSTRAINT historique_exports_pkey PRIMARY KEY (id),
  CONSTRAINT historique_exports_export_programme_id_fkey FOREIGN KEY (export_programme_id) REFERENCES public.exports_programmes(id),
  CONSTRAINT historique_exports_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates_export(id)
);
CREATE TABLE public.historique_taches_automatisees (
  id bigint NOT NULL DEFAULT nextval('historique_taches_automatisees_id_seq'::regclass),
  tache_id bigint,
  date_debut_execution timestamp with time zone DEFAULT now(),
  date_fin_execution timestamp with time zone,
  statut character varying NOT NULL CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'erreur'::character varying, 'annule'::character varying]::text[])),
  resultat jsonb,
  message_erreur text,
  duree_execution integer,
  ressources_utilisees jsonb,
  CONSTRAINT historique_taches_automatisees_pkey PRIMARY KEY (id),
  CONSTRAINT historique_taches_automatisees_tache_id_fkey FOREIGN KEY (tache_id) REFERENCES public.taches_automatisees(id)
);
CREATE TABLE public.instructions_diverses (
  id integer NOT NULL DEFAULT nextval('instructions_diverses_id_seq'::regclass),
  consultation_id bigint,
  patient_id bigint,
  type_instruction character varying NOT NULL,
  titre character varying NOT NULL,
  description text NOT NULL,
  urgence boolean DEFAULT false,
  date_instruction date DEFAULT CURRENT_DATE,
  date_execution date,
  statut character varying DEFAULT 'en_attente'::character varying CHECK (statut::text = ANY (ARRAY['en_attente'::character varying, 'en_cours'::character varying, 'termine'::character varying, 'annule'::character varying]::text[])),
  traite_par bigint,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT instructions_diverses_pkey PRIMARY KEY (id),
  CONSTRAINT fk_instructions_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_instructions_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_instructions_traite_par FOREIGN KEY (traite_par) REFERENCES public.users(id),
  CONSTRAINT fk_instructions_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_instructions_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.invoices (
  id bigint NOT NULL DEFAULT nextval('invoices_id_seq'::regclass),
  patient_id bigint NOT NULL,
  consultation_id bigint,
  montant numeric NOT NULL,
  statut_paiement character varying NOT NULL CHECK (statut_paiement::text = ANY (ARRAY['paye'::character varying, 'en_attente'::character varying, 'impaye'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT fk_invoices_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_invoices_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.lignes_facture (
  id integer NOT NULL DEFAULT nextval('lignes_facture_id_seq'::regclass),
  facture_id bigint,
  acte_consultation_id bigint,
  description character varying NOT NULL,
  quantite integer DEFAULT 1,
  prix_unitaire numeric NOT NULL,
  montant_ligne numeric DEFAULT ((quantite)::numeric * prix_unitaire),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lignes_facture_pkey PRIMARY KEY (id),
  CONSTRAINT fk_lignes_facture_facture FOREIGN KEY (facture_id) REFERENCES public.factures(id),
  CONSTRAINT fk_lignes_facture_acte FOREIGN KEY (acte_consultation_id) REFERENCES public.actes_consultation(id)
);
CREATE TABLE public.lignes_ordonnance (
  id bigint NOT NULL DEFAULT nextval('lignes_ordonnance_id_seq'::regclass),
  ordonnance_id bigint NOT NULL,
  medicament_id bigint NOT NULL,
  posologie text NOT NULL,
  quantite integer DEFAULT 1,
  duree_traitement character varying,
  instructions_particulieres text,
  moment_prise character varying DEFAULT 'matin'::character varying,
  avec_repas boolean DEFAULT false,
  urgent boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lignes_ordonnance_pkey PRIMARY KEY (id),
  CONSTRAINT lignes_ordonnance_ordonnance_id_fkey FOREIGN KEY (ordonnance_id) REFERENCES public.ordonnances(id),
  CONSTRAINT lignes_ordonnance_medicament_id_fkey FOREIGN KEY (medicament_id) REFERENCES public.medicaments(id)
);
CREATE TABLE public.liste_maladies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nom character varying NOT NULL UNIQUE,
  code_cim character varying,
  description text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT liste_maladies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.liste_periodes (
  id bigint NOT NULL DEFAULT nextval('liste_periodes_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT liste_periodes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.liste_produits (
  id bigint NOT NULL DEFAULT nextval('liste_produits_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  code_atc character varying,
  fabricant character varying,
  prix numeric DEFAULT 0,
  stock integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT liste_produits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.liste_vaccins (
  id bigint NOT NULL DEFAULT nextval('liste_vaccins_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  code_atc character varying,
  fabricant character varying,
  prix numeric DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT liste_vaccins_pkey PRIMARY KEY (id)
);
CREATE TABLE public.maladies (
  id bigint NOT NULL DEFAULT nextval('maladies_id_seq'::regclass),
  nom character varying NOT NULL,
  code_cim character varying,
  description text,
  specialite_id bigint,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT maladies_pkey PRIMARY KEY (id),
  CONSTRAINT fk_maladies_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id)
);
CREATE TABLE public.manual_passwords (
  id bigint NOT NULL DEFAULT nextval('manual_passwords_id_seq'::regclass),
  user_email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT manual_passwords_pkey PRIMARY KEY (id)
);
CREATE TABLE public.medecin_specialites (
  id bigint NOT NULL DEFAULT nextval('medecin_specialites_id_seq'::regclass),
  medecin_id bigint NOT NULL,
  specialite_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medecin_specialites_pkey PRIMARY KEY (id),
  CONSTRAINT medecin_specialites_medecin_id_fkey FOREIGN KEY (medecin_id) REFERENCES public.users(id),
  CONSTRAINT medecin_specialites_specialite_id_fkey FOREIGN KEY (specialite_id) REFERENCES public.specialites(id)
);
CREATE TABLE public.medicaments (
  id bigint NOT NULL DEFAULT nextval('medicaments_id_seq'::regclass),
  nom character varying NOT NULL UNIQUE,
  description text,
  forme_pharmaceutique character varying,
  dosage character varying,
  posologie_defaut text,
  contre_indications text,
  interactions text,
  specialite_id bigint,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  dci character varying,
  voie_administration character varying,
  classe_therapeutique character varying,
  effets_indesirables text,
  posologie_adulte text,
  posologie_enfant text,
  CONSTRAINT medicaments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_medicaments_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_medicaments_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_medicaments_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.modeles_consultation (
  id integer NOT NULL DEFAULT nextval('modeles_consultation_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  type_consultation character varying NOT NULL,
  specialite_id integer,
  elements_par_defaut jsonb,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modeles_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT modeles_consultation_specialite_id_fkey FOREIGN KEY (specialite_id) REFERENCES public.specialites(id)
);
CREATE TABLE public.modeles_ia (
  id bigint NOT NULL DEFAULT nextval('modeles_ia_id_seq'::regclass),
  nom_modele character varying NOT NULL,
  description text,
  type_modele character varying NOT NULL CHECK (type_modele::text = ANY (ARRAY['prevision'::character varying, 'classification'::character varying, 'anomalie'::character varying, 'optimisation'::character varying]::text[])),
  algorithme character varying NOT NULL,
  version character varying NOT NULL,
  parametres_modele jsonb,
  metriques_performance jsonb,
  statut character varying DEFAULT 'entraine'::character varying CHECK (statut::text = ANY (ARRAY['entraine'::character varying, 'entrainement'::character varying, 'test'::character varying, 'production'::character varying, 'archive'::character varying]::text[])),
  precision_modele numeric,
  date_entrainement timestamp with time zone,
  date_mise_production timestamp with time zone,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modeles_ia_pkey PRIMARY KEY (id),
  CONSTRAINT modeles_ia_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.modeles_rapports (
  id bigint NOT NULL DEFAULT nextval('modeles_rapports_id_seq'::regclass),
  nom_modele character varying NOT NULL,
  description text,
  type_rapport character varying NOT NULL,
  parametres_defaut jsonb,
  colonnes_a_inclure jsonb,
  filtres_defaut jsonb,
  ordre_tri jsonb,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modeles_rapports_pkey PRIMARY KEY (id),
  CONSTRAINT modeles_rapports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications_consultation (
  id integer NOT NULL DEFAULT nextval('notifications_consultation_id_seq'::regclass),
  consultation_id integer,
  destinataire_id bigint,
  type_notification character varying NOT NULL,
  titre character varying NOT NULL,
  message text NOT NULL,
  priorite character varying DEFAULT 'normale'::character varying CHECK (priorite::text = ANY (ARRAY['basse'::character varying, 'normale'::character varying, 'haute'::character varying, 'urgente'::character varying]::text[])),
  lu boolean DEFAULT false,
  action_url character varying,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_consultation_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT notifications_consultation_destinataire_id_fkey FOREIGN KEY (destinataire_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications_medecin_secretaire (
  id bigint NOT NULL DEFAULT nextval('notifications_medecin_secretaire_id_seq'::regclass),
  type_notification character varying DEFAULT 'general'::character varying,
  titre character varying,
  message text NOT NULL,
  medecin_id bigint NOT NULL,
  secretaire_id bigint NOT NULL,
  patient_id bigint,
  waiting_queue_id bigint,
  lu boolean DEFAULT false,
  lu_at timestamp with time zone,
  priorite character varying DEFAULT 'normale'::character varying CHECK (priorite::text = ANY (ARRAY['normale'::character varying, 'urgente'::character varying, 'importante'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  type character varying DEFAULT 'general'::character varying,
  consultation_id bigint,
  CONSTRAINT notifications_medecin_secretaire_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_medecin_secretaire_medecin_id_fkey FOREIGN KEY (medecin_id) REFERENCES public.users(id),
  CONSTRAINT notifications_medecin_secretaire_secretaire_id_fkey FOREIGN KEY (secretaire_id) REFERENCES public.users(id),
  CONSTRAINT notifications_medecin_secretaire_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT notifications_medecin_secretaire_waiting_queue_id_fkey FOREIGN KEY (waiting_queue_id) REFERENCES public.waiting_queue(id),
  CONSTRAINT notifications_medecin_secretaire_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.notifications_push (
  id bigint NOT NULL DEFAULT nextval('notifications_push_id_seq'::regclass),
  titre character varying NOT NULL,
  message text NOT NULL,
  type_notification character varying NOT NULL CHECK (type_notification::text = ANY (ARRAY['alerte'::character varying, 'rapport'::character varying, 'systeme'::character varying, 'utilisateur'::character varying]::text[])),
  priorite character varying DEFAULT 'normale'::character varying CHECK (priorite::text = ANY (ARRAY['basse'::character varying, 'normale'::character varying, 'haute'::character varying, 'critique'::character varying]::text[])),
  destinataires jsonb,
  donnees_contexte jsonb,
  statut character varying DEFAULT 'en_attente'::character varying CHECK (statut::text = ANY (ARRAY['en_attente'::character varying, 'envoyee'::character varying, 'lue'::character varying, 'traitee'::character varying]::text[])),
  date_creation timestamp with time zone DEFAULT now(),
  date_envoi timestamp with time zone,
  date_lecture timestamp with time zone,
  created_by bigint,
  CONSTRAINT notifications_push_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_push_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.notifications_simple (
  id bigint NOT NULL DEFAULT nextval('notifications_simple_id_seq'::regclass),
  type_notification character varying NOT NULL CHECK (type_notification::text = ANY (ARRAY['medecin_disponible'::character varying, 'patient_autorise'::character varying, 'consultation_terminee'::character varying]::text[])),
  medecin_id bigint NOT NULL,
  secretaire_id bigint NOT NULL,
  patient_id bigint NOT NULL,
  waiting_queue_id bigint,
  message text NOT NULL,
  lu boolean DEFAULT false,
  lu_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:30:00'::interval),
  CONSTRAINT notifications_simple_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_simple_medecin_id_fkey FOREIGN KEY (medecin_id) REFERENCES public.users(id),
  CONSTRAINT notifications_simple_secretaire_id_fkey FOREIGN KEY (secretaire_id) REFERENCES public.users(id),
  CONSTRAINT notifications_simple_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT notifications_simple_waiting_queue_id_fkey FOREIGN KEY (waiting_queue_id) REFERENCES public.waiting_queue(id)
);
CREATE TABLE public.ordonnances (
  id bigint NOT NULL DEFAULT nextval('ordonnances_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  numero_ordonnance character varying UNIQUE,
  date_prescription date DEFAULT CURRENT_DATE,
  statut character varying DEFAULT 'active'::character varying CHECK (statut::text = ANY (ARRAY['active'::character varying, 'terminee'::character varying, 'annulee'::character varying]::text[])),
  instructions_generales text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  prochain_rdv text,
  CONSTRAINT ordonnances_pkey PRIMARY KEY (id),
  CONSTRAINT ordonnances_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.parametres_cabinet (
  id bigint NOT NULL DEFAULT nextval('parametres_cabinet_id_seq'::regclass),
  nom_cabinet character varying,
  adresse text,
  ville character varying,
  code_postal character varying,
  pays character varying DEFAULT 'Niger'::character varying,
  telephone character varying,
  email character varying,
  site_web character varying,
  numero_agrement character varying,
  ninea character varying,
  registre_commerce character varying,
  tva numeric DEFAULT 0,
  logo_url character varying,
  devise character varying DEFAULT 'FCFA'::character varying,
  fuseau_horaire character varying DEFAULT 'Africa/Niamey'::character varying,
  langue character varying DEFAULT 'fr'::character varying,
  format_date character varying DEFAULT 'DD/MM/YYYY'::character varying,
  horaires_ouverture jsonb DEFAULT '{"jeudi": {"fin": "18:00", "debut": "08:00", "ouvert": true}, "lundi": {"fin": "18:00", "debut": "08:00", "ouvert": true}, "mardi": {"fin": "18:00", "debut": "08:00", "ouvert": true}, "samedi": {"fin": "12:00", "debut": "08:00", "ouvert": false}, "dimanche": {"fin": "", "debut": "", "ouvert": false}, "mercredi": {"fin": "18:00", "debut": "08:00", "ouvert": true}, "vendredi": {"fin": "18:00", "debut": "08:00", "ouvert": true}}'::jsonb,
  mode_specialite_id bigint,
  created_by bigint,
  updated_by bigint,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT parametres_cabinet_pkey PRIMARY KEY (id),
  CONSTRAINT parametres_cabinet_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT parametres_cabinet_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT parametres_cabinet_mode_specialite_id_fkey FOREIGN KEY (mode_specialite_id) REFERENCES public.specialites(id)
);
CREATE TABLE public.patient_documents (
  id bigint NOT NULL DEFAULT nextval('patient_documents_id_seq'::regclass),
  patient_id bigint NOT NULL,
  type_document character varying NOT NULL CHECK (type_document::text = ANY (ARRAY['analyse'::character varying, 'radio'::character varying, 'echographie'::character varying, 'scanner'::character varying, 'irm'::character varying, 'ordonnance_externe'::character varying, 'certificat_medical'::character varying, 'compte_rendu'::character varying, 'autre'::character varying]::text[])),
  nom_fichier character varying NOT NULL,
  fichier_url character varying NOT NULL,
  date_document date NOT NULL,
  uploaded_by uuid NOT NULL,
  notes text,
  taille_fichier bigint,
  type_mime character varying,
  consultation_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT patient_documents_pkey PRIMARY KEY (id),
  CONSTRAINT patient_documents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id),
  CONSTRAINT patient_documents_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.patients (
  id bigint NOT NULL DEFAULT nextval('patients_id_seq'::regclass),
  nom character varying NOT NULL,
  prenom character varying NOT NULL,
  date_naissance date NOT NULL,
  telephone character varying,
  adresse character varying,
  assurance character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  numero_dossier character varying UNIQUE,
  email character varying,
  sexe character varying CHECK (sexe::text = ANY (ARRAY['M'::character varying, 'F'::character varying]::text[])),
  lieu_naissance character varying,
  nationalite character varying,
  profession character varying,
  situation_familiale character varying,
  personne_contact character varying,
  telephone_contact character varying,
  lien_contact character varying,
  medecin_traitant character varying,
  numero_secu character varying,
  mutuelle character varying,
  numero_mutuelle character varying,
  actif boolean DEFAULT true,
  notes text,
  numero_ipm character varying,
  medecin_traitant_id bigint,
  groupe_sanguin character varying,
  assurance_id bigint,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_medecin_traitant_id_fkey FOREIGN KEY (medecin_traitant_id) REFERENCES public.users(id),
  CONSTRAINT patients_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT patients_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT fk_patients_assurance FOREIGN KEY (assurance_id) REFERENCES public.assurances(id)
);
CREATE TABLE public.periodes_comparaison (
  id bigint NOT NULL DEFAULT nextval('periodes_comparaison_id_seq'::regclass),
  nom_comparaison character varying NOT NULL,
  description text,
  periode_reference jsonb NOT NULL,
  periode_comparaison jsonb NOT NULL,
  metriques_a_comparer jsonb NOT NULL,
  seuil_significatif numeric DEFAULT 5.0,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT periodes_comparaison_pkey PRIMARY KEY (id),
  CONSTRAINT periodes_comparaison_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.permissions_tableau_bord (
  id bigint NOT NULL DEFAULT nextval('permissions_tableau_bord_id_seq'::regclass),
  tableau_bord_id bigint,
  user_id bigint,
  role_permission character varying NOT NULL CHECK (role_permission::text = ANY (ARRAY['lecture'::character varying, 'modification'::character varying, 'administration'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT permissions_tableau_bord_pkey PRIMARY KEY (id),
  CONSTRAINT permissions_tableau_bord_tableau_bord_id_fkey FOREIGN KEY (tableau_bord_id) REFERENCES public.tableaux_bord_personnalises(id),
  CONSTRAINT permissions_tableau_bord_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.posologie_produits (
  id bigint NOT NULL DEFAULT nextval('posologie_produits_id_seq'::regclass),
  produit_id bigint NOT NULL,
  posologie text NOT NULL,
  duree_traitement character varying,
  instructions text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT posologie_produits_pkey PRIMARY KEY (id),
  CONSTRAINT fk_posologie_produit FOREIGN KEY (produit_id) REFERENCES public.liste_produits(id)
);
CREATE TABLE public.predictions_ia (
  id bigint NOT NULL DEFAULT nextval('predictions_ia_id_seq'::regclass),
  modele_id bigint,
  type_prediction character varying NOT NULL,
  donnees_entree jsonb NOT NULL,
  prediction jsonb NOT NULL,
  confiance numeric,
  intervalle_confiance jsonb,
  date_prediction timestamp with time zone DEFAULT now(),
  date_validation timestamp with time zone,
  valide boolean,
  commentaire_validation text,
  CONSTRAINT predictions_ia_pkey PRIMARY KEY (id),
  CONSTRAINT predictions_ia_modele_id_fkey FOREIGN KEY (modele_id) REFERENCES public.modeles_ia(id)
);
CREATE TABLE public.preferences_notifications (
  id bigint NOT NULL DEFAULT nextval('preferences_notifications_id_seq'::regclass),
  user_id bigint,
  type_notification character varying NOT NULL,
  canal_notification character varying NOT NULL CHECK (canal_notification::text = ANY (ARRAY['email'::character varying, 'push'::character varying, 'sms'::character varying, 'webhook'::character varying]::text[])),
  actif boolean DEFAULT true,
  frequence character varying DEFAULT 'immediate'::character varying CHECK (frequence::text = ANY (ARRAY['immediate'::character varying, 'quotidien'::character varying, 'hebdomadaire'::character varying]::text[])),
  heures_autorisees jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT preferences_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT preferences_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.prescriptions (
  id bigint NOT NULL DEFAULT nextval('prescriptions_id_seq'::regclass),
  medicaments text NOT NULL,
  posologie text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  date_prescription date DEFAULT CURRENT_DATE,
  statut character varying DEFAULT 'active'::character varying CHECK (statut::text = ANY (ARRAY['active'::character varying, 'terminee'::character varying, 'annulee'::character varying]::text[])),
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_prescriptions_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.prescriptions_pharmacie (
  id integer NOT NULL DEFAULT nextval('prescriptions_pharmacie_id_seq'::regclass),
  consultation_id bigint,
  patient_id bigint,
  medicament_id bigint,
  posologie text NOT NULL,
  duree_traitement character varying,
  quantite_prescrite integer,
  unite character varying,
  renouvellements integer DEFAULT 0,
  urgence boolean DEFAULT false,
  date_prescription date DEFAULT CURRENT_DATE,
  date_debut_traitement date,
  statut character varying DEFAULT 'prescrit'::character varying CHECK (statut::text = ANY (ARRAY['prescrit'::character varying, 'delivre'::character varying, 'termine'::character varying, 'annule'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT prescriptions_pharmacie_pkey PRIMARY KEY (id),
  CONSTRAINT fk_prescriptions_pharmacie_consultation FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT fk_prescriptions_pharmacie_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_prescriptions_pharmacie_medicament FOREIGN KEY (medicament_id) REFERENCES public.medicaments(id),
  CONSTRAINT fk_prescriptions_pharmacie_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_prescriptions_pharmacie_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.previsions (
  id bigint NOT NULL DEFAULT nextval('previsions_id_seq'::regclass),
  nom_prevision character varying NOT NULL,
  type_prevision character varying NOT NULL CHECK (type_prevision::text = ANY (ARRAY['consultations'::character varying, 'revenus'::character varying, 'patients'::character varying, 'charge_travail'::character varying]::text[])),
  modele_utilise character varying NOT NULL CHECK (modele_utilise::text = ANY (ARRAY['lineaire'::character varying, 'saisonniere'::character varying, 'moyenne_mobile'::character varying, 'exponentielle'::character varying]::text[])),
  horizon_prevision integer NOT NULL,
  donnees_historiques jsonb NOT NULL,
  resultats_prevision jsonb NOT NULL,
  precision_modele numeric,
  date_creation timestamp with time zone DEFAULT now(),
  created_by bigint,
  CONSTRAINT previsions_pkey PRIMARY KEY (id),
  CONSTRAINT previsions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.professions (
  id bigint NOT NULL DEFAULT nextval('professions_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  code character varying,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT professions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rappels_sms (
  id bigint NOT NULL DEFAULT nextval('rappels_sms_id_seq'::regclass),
  appointment_id bigint NOT NULL,
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  type_rappel character varying NOT NULL CHECK (type_rappel::text = ANY (ARRAY['veille'::character varying, 'jour_j'::character varying, 'annulation'::character varying, 'modification'::character varying]::text[])),
  numero_telephone character varying NOT NULL,
  message text NOT NULL,
  statut character varying DEFAULT 'en_attente'::character varying CHECK (statut::text = ANY (ARRAY['en_attente'::character varying, 'envoye'::character varying, 'delivre'::character varying, 'erreur'::character varying]::text[])),
  date_envoi timestamp with time zone,
  reponse_sms text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rappels_sms_pkey PRIMARY KEY (id),
  CONSTRAINT fk_rappels_sms_appointment FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT fk_rappels_sms_patient FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT fk_rappels_sms_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.rapports_consultation (
  id integer NOT NULL DEFAULT nextval('rapports_consultation_id_seq'::regclass),
  consultation_id integer,
  type_rapport character varying NOT NULL,
  format_rapport character varying NOT NULL,
  url_fichier character varying,
  taille_fichier integer,
  statut character varying DEFAULT 'en_cours'::character varying CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'erreur'::character varying]::text[])),
  parametres_generation jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rapports_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT rapports_consultation_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.rapports_exportables (
  id bigint NOT NULL DEFAULT nextval('rapports_exportables_id_seq'::regclass),
  nom_rapport character varying NOT NULL,
  type_rapport character varying NOT NULL CHECK (type_rapport::text = ANY (ARRAY['consultations'::character varying, 'finances'::character varying, 'actes'::character varying, 'patients'::character varying, 'medecins'::character varying, 'complet'::character varying]::text[])),
  format_export character varying NOT NULL CHECK (format_export::text = ANY (ARRAY['pdf'::character varying, 'excel'::character varying, 'csv'::character varying, 'json'::character varying]::text[])),
  parametres_filtres jsonb,
  date_debut date,
  date_fin date,
  statut character varying DEFAULT 'en_cours'::character varying CHECK (statut::text = ANY (ARRAY['en_cours'::character varying, 'termine'::character varying, 'erreur'::character varying, 'annule'::character varying]::text[])),
  url_fichier character varying,
  taille_fichier bigint,
  duree_generation integer,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT rapports_exportables_pkey PRIMARY KEY (id),
  CONSTRAINT rapports_exportables_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.regles_alertes (
  id bigint NOT NULL DEFAULT nextval('regles_alertes_id_seq'::regclass),
  nom_regle character varying NOT NULL,
  description text,
  type_alerte character varying NOT NULL CHECK (type_alerte::text = ANY (ARRAY['seuil'::character varying, 'tendance'::character varying, 'anomalie'::character varying, 'absence'::character varying, 'retard'::character varying]::text[])),
  condition_alerte jsonb NOT NULL,
  seuil_valeur numeric,
  periode_verification integer,
  statut character varying DEFAULT 'active'::character varying CHECK (statut::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pause'::character varying]::text[])),
  priorite character varying DEFAULT 'normale'::character varying CHECK (priorite::text = ANY (ARRAY['basse'::character varying, 'normale'::character varying, 'haute'::character varying, 'critique'::character varying]::text[])),
  destinataires jsonb,
  message_template text,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT regles_alertes_pkey PRIMARY KEY (id),
  CONSTRAINT regles_alertes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.regles_alertes_avancees (
  id bigint NOT NULL DEFAULT nextval('regles_alertes_avancees_id_seq'::regclass),
  nom_regle character varying NOT NULL,
  description text,
  type_alerte character varying NOT NULL CHECK (type_alerte::text = ANY (ARRAY['anomalie'::character varying, 'tendance'::character varying, 'seuil_dynamique'::character varying, 'correlation'::character varying]::text[])),
  algorithme_detection character varying NOT NULL,
  parametres_algorithme jsonb NOT NULL,
  seuil_sensibilite numeric DEFAULT 0.8,
  periode_analyse integer,
  conditions_declenchement jsonb,
  actions_automatiques jsonb,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT regles_alertes_avancees_pkey PRIMARY KEY (id),
  CONSTRAINT regles_alertes_avancees_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.relances (
  id bigint NOT NULL DEFAULT nextval('relances_id_seq'::regclass),
  facture_id bigint NOT NULL,
  date_relance date NOT NULL,
  type_relance character varying NOT NULL,
  montant_relance numeric NOT NULL,
  notes text,
  statut character varying DEFAULT 'envoyee'::character varying CHECK (statut::text = ANY (ARRAY['envoyee'::character varying, 'payee'::character varying, 'annulee'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT relances_pkey PRIMARY KEY (id),
  CONSTRAINT fk_relances_facture FOREIGN KEY (facture_id) REFERENCES public.factures_old(id),
  CONSTRAINT relances_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.resultats_comparaison (
  id bigint NOT NULL DEFAULT nextval('resultats_comparaison_id_seq'::regclass),
  periode_comparaison_id bigint,
  metrique character varying NOT NULL,
  valeur_reference numeric NOT NULL,
  valeur_comparaison numeric NOT NULL,
  variation_absolue numeric NOT NULL,
  variation_relative numeric NOT NULL,
  significatif boolean DEFAULT false,
  interpretation text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resultats_comparaison_pkey PRIMARY KEY (id),
  CONSTRAINT resultats_comparaison_periode_comparaison_id_fkey FOREIGN KEY (periode_comparaison_id) REFERENCES public.periodes_comparaison(id)
);
CREATE TABLE public.signes_cliniques (
  id bigint NOT NULL DEFAULT nextval('signes_cliniques_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  categorie character varying DEFAULT 'generale'::character varying,
  type_signe character varying DEFAULT 'observation'::character varying CHECK (type_signe::text = ANY (ARRAY['observation'::character varying, 'palpation'::character varying, 'percussion'::character varying, 'auscultation'::character varying]::text[])),
  localisation character varying,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT signes_cliniques_pkey PRIMARY KEY (id),
  CONSTRAINT fk_signes_cliniques_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_signes_cliniques_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.signes_cliniques_consultation (
  id bigint NOT NULL DEFAULT nextval('signes_cliniques_consultation_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  signe_clinique_id bigint NOT NULL,
  intensite character varying DEFAULT 'moderee'::character varying CHECK (intensite::text = ANY (ARRAY['faible'::character varying, 'moderee'::character varying, 'forte'::character varying]::text[])),
  localisation character varying,
  commentaires text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signes_cliniques_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT signes_cliniques_consultation_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT signes_cliniques_consultation_signe_clinique_id_fkey FOREIGN KEY (signe_clinique_id) REFERENCES public.signes_cliniques(id)
);
CREATE TABLE public.soins (
  id bigint NOT NULL DEFAULT nextval('soins_id_seq'::regclass),
  acte_id bigint NOT NULL,
  type_soin character varying NOT NULL,
  description text,
  duree integer,
  materiel_utilise text,
  notes text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT soins_pkey PRIMARY KEY (id),
  CONSTRAINT fk_soins_acte FOREIGN KEY (acte_id) REFERENCES public.actes(id)
);
CREATE TABLE public.specialites (
  id bigint NOT NULL DEFAULT nextval('specialites_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  color character varying DEFAULT '#3b82f6'::character varying,
  CONSTRAINT specialites_pkey PRIMARY KEY (id)
);
CREATE TABLE public.statistiques_consultations (
  id bigint NOT NULL DEFAULT nextval('statistiques_consultations_id_seq'::regclass),
  date_statistique date NOT NULL,
  medecin_id bigint,
  nombre_consultations integer DEFAULT 0,
  nombre_patients integer DEFAULT 0,
  duree_moyenne numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT statistiques_consultations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_statistiques_medecin FOREIGN KEY (medecin_id) REFERENCES public.users(id)
);
CREATE TABLE public.syntheses_consultation (
  id bigint NOT NULL DEFAULT nextval('syntheses_consultation_id_seq'::regclass),
  consultation_id bigint NOT NULL,
  element_synthese_id bigint NOT NULL,
  commentaires text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT syntheses_consultation_pkey PRIMARY KEY (id),
  CONSTRAINT syntheses_consultation_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT syntheses_consultation_element_synthese_id_fkey FOREIGN KEY (element_synthese_id) REFERENCES public.elements_synthese(id)
);
CREATE TABLE public.tableau_bord_widgets (
  id bigint NOT NULL DEFAULT nextval('tableau_bord_widgets_id_seq'::regclass),
  tableau_bord_id bigint,
  widget_id bigint,
  position_x integer DEFAULT 0,
  position_y integer DEFAULT 0,
  largeur integer DEFAULT 1,
  hauteur integer DEFAULT 1,
  ordre_affichage integer DEFAULT 0,
  CONSTRAINT tableau_bord_widgets_pkey PRIMARY KEY (id),
  CONSTRAINT tableau_bord_widgets_tableau_bord_id_fkey FOREIGN KEY (tableau_bord_id) REFERENCES public.tableaux_bord_personnalises(id),
  CONSTRAINT tableau_bord_widgets_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.widgets_tableau_bord(id)
);
CREATE TABLE public.tableaux_bord_personnalises (
  id bigint NOT NULL DEFAULT nextval('tableaux_bord_personnalises_id_seq'::regclass),
  nom_tableau character varying NOT NULL,
  description text,
  configuration_layout jsonb,
  parametres_rafraichissement jsonb,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tableaux_bord_personnalises_pkey PRIMARY KEY (id),
  CONSTRAINT tableaux_bord_personnalises_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.taches_automatisees (
  id bigint NOT NULL DEFAULT nextval('taches_automatisees_id_seq'::regclass),
  nom_tache character varying NOT NULL,
  description text,
  type_tache character varying NOT NULL CHECK (type_tache::text = ANY (ARRAY['rapport'::character varying, 'alerte'::character varying, 'nettoyage'::character varying, 'sauvegarde'::character varying, 'analyse'::character varying]::text[])),
  frequence character varying NOT NULL CHECK (frequence::text = ANY (ARRAY['quotidien'::character varying, 'hebdomadaire'::character varying, 'mensuel'::character varying, 'trimestriel'::character varying, 'annuel'::character varying]::text[])),
  parametres_execution jsonb,
  derniere_execution timestamp with time zone,
  prochaine_execution timestamp with time zone,
  statut character varying DEFAULT 'actif'::character varying CHECK (statut::text = ANY (ARRAY['actif'::character varying, 'inactif'::character varying, 'pause'::character varying, 'erreur'::character varying]::text[])),
  nombre_executions integer DEFAULT 0,
  nombre_erreurs integer DEFAULT 0,
  duree_moyenne_execution integer,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT taches_automatisees_pkey PRIMARY KEY (id),
  CONSTRAINT taches_automatisees_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.tarifs_actes (
  id integer NOT NULL DEFAULT nextval('tarifs_actes_id_seq'::regclass),
  type_acte_id bigint,
  specialite_id bigint,
  tarif_base numeric NOT NULL,
  tarif_secu numeric,
  tarif_mutuelle numeric,
  date_debut_validite date DEFAULT CURRENT_DATE,
  date_fin_validite date,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT tarifs_actes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_tarifs_type_acte FOREIGN KEY (type_acte_id) REFERENCES public.types_actes(id),
  CONSTRAINT fk_tarifs_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_tarifs_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_tarifs_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.templates_export (
  id bigint NOT NULL DEFAULT nextval('templates_export_id_seq'::regclass),
  nom_template character varying NOT NULL,
  description text,
  type_export character varying NOT NULL CHECK (type_export::text = ANY (ARRAY['pdf'::character varying, 'excel'::character varying, 'csv'::character varying, 'json'::character varying, 'xml'::character varying, 'api'::character varying]::text[])),
  format_template jsonb NOT NULL,
  parametres_defaut jsonb,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT templates_export_pkey PRIMARY KEY (id),
  CONSTRAINT templates_export_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.themes_tableau_bord (
  id bigint NOT NULL DEFAULT nextval('themes_tableau_bord_id_seq'::regclass),
  nom_theme character varying NOT NULL,
  description text,
  configuration_theme jsonb NOT NULL,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT themes_tableau_bord_pkey PRIMARY KEY (id),
  CONSTRAINT themes_tableau_bord_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.types_actes (
  id bigint NOT NULL DEFAULT nextval('types_actes_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  tarif_defaut numeric,
  specialite_id bigint,
  duree_estimee integer,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT types_actes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_types_actes_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_types_actes_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_types_actes_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.types_analyses_labo (
  id integer NOT NULL DEFAULT nextval('types_analyses_labo_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  code_analyse character varying,
  valeurs_normales text,
  unite character varying,
  delai_resultat integer,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT types_analyses_labo_pkey PRIMARY KEY (id),
  CONSTRAINT fk_types_analyses_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_types_analyses_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.types_archives (
  id bigint NOT NULL DEFAULT nextval('types_archives_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT types_archives_pkey PRIMARY KEY (id)
);
CREATE TABLE public.types_certificats (
  id bigint NOT NULL DEFAULT nextval('types_certificats_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  duree_defaut integer,
  specialite_id bigint,
  ordre_affichage integer DEFAULT 0,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT types_certificats_pkey PRIMARY KEY (id),
  CONSTRAINT fk_types_certificats_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_types_certificats_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_types_certificats_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.types_examens (
  id integer NOT NULL DEFAULT nextval('types_examens_id_seq'::regclass),
  nom character varying NOT NULL,
  description text,
  specialite_id bigint,
  duree_estimee integer,
  preparation_requise text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by bigint,
  updated_by bigint,
  CONSTRAINT types_examens_pkey PRIMARY KEY (id),
  CONSTRAINT fk_types_examens_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT fk_types_examens_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_types_examens_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email character varying NOT NULL UNIQUE,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['secretary'::character varying, 'doctor'::character varying, 'admin'::character varying]::text[])),
  nom character varying NOT NULL,
  prenom character varying NOT NULL,
  specialite character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  telephone character varying,
  specialite_id bigint,
  horaires_travail jsonb,
  duree_consultation integer DEFAULT 30,
  actif boolean DEFAULT true,
  photo_url character varying,
  auth_id uuid,
  current_patient_id bigint,
  selected_current_patient_id bigint,
  username character varying NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_current_patient_id_fkey FOREIGN KEY (current_patient_id) REFERENCES public.waiting_queue(id),
  CONSTRAINT fk_users_specialite FOREIGN KEY (specialite_id) REFERENCES public.specialites(id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vaccinations (
  id bigint NOT NULL DEFAULT nextval('vaccinations_id_seq'::regclass),
  acte_id bigint NOT NULL,
  vaccin_id bigint NOT NULL,
  dose character varying,
  voie_administration character varying,
  lot character varying,
  date_expiration date,
  notes text,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vaccinations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_vaccinations_acte FOREIGN KEY (acte_id) REFERENCES public.actes(id),
  CONSTRAINT fk_vaccinations_vaccin FOREIGN KEY (vaccin_id) REFERENCES public.liste_vaccins(id)
);
CREATE TABLE public.waiting_queue (
  id bigint NOT NULL DEFAULT nextval('waiting_queue_id_seq'::regclass),
  patient_id bigint NOT NULL,
  medecin_id bigint NOT NULL,
  order_position integer NOT NULL,
  status character varying NOT NULL DEFAULT 'en_attente'::character varying CHECK (status::text = ANY (ARRAY['waiting'::character varying, 'present'::character varying, 'in_consultation'::character varying, 'late'::character varying, 'emergency'::character varying, 'arrive'::character varying, 'appele'::character varying, 'entre'::character varying, 'termine'::character varying, 'absent'::character varying, 'reporte'::character varying, 'urgence'::character varying, 'en_attente'::character varying, 'authorized'::character varying, 'medecin_pret'::character varying, 'en_route'::character varying]::text[])),
  arrived_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  added_by bigint,
  documents_scannes text,
  motif_consultation text,
  temps_attente_estime integer,
  notification_envoyee boolean DEFAULT false,
  appointment_id bigint,
  priority character varying DEFAULT 'normale'::character varying,
  medecin_disponible boolean DEFAULT false,
  medecin_pret_at timestamp with time zone,
  secretaire_confirme_at timestamp with time zone,
  temps_attente_reel integer,
  position_originale bigint,
  notes_secretaire text,
  notes_medecin text,
  secretaire_notifie_at timestamp with time zone,
  patient_envoye_at timestamp with time zone,
  consultation_terminee_at timestamp with time zone,
  called_by_doctor_id bigint,
  called_at timestamp with time zone,
  authorized_at timestamp with time zone,
  consultation_started_at timestamp with time zone,
  consultation_ended_at timestamp with time zone,
  current_location character varying,
  secretary_notes text,
  doctor_notes text,
  CONSTRAINT waiting_queue_pkey PRIMARY KEY (id),
  CONSTRAINT waiting_queue_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.widgets_tableau_bord (
  id bigint NOT NULL DEFAULT nextval('widgets_tableau_bord_id_seq'::regclass),
  nom_widget character varying NOT NULL,
  type_widget character varying NOT NULL CHECK (type_widget::text = ANY (ARRAY['graphique'::character varying, 'metrique'::character varying, 'tableau'::character varying, 'calendrier'::character varying, 'liste'::character varying]::text[])),
  titre character varying NOT NULL,
  description text,
  configuration jsonb NOT NULL,
  position_x integer DEFAULT 0,
  position_y integer DEFAULT 0,
  largeur integer DEFAULT 1,
  hauteur integer DEFAULT 1,
  actif boolean DEFAULT true,
  created_by bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT widgets_tableau_bord_pkey PRIMARY KEY (id),
  CONSTRAINT widgets_tableau_bord_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.workflow_notifications (
  id bigint NOT NULL DEFAULT nextval('workflow_notifications_id_seq'::regclass),
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['patient_present'::character varying, 'doctor_called_patient'::character varying, 'patient_called'::character varying, 'patient_authorized'::character varying, 'consultation_started'::character varying, 'consultation_ended'::character varying]::text[])),
  from_user_id bigint NOT NULL,
  to_user_id bigint NOT NULL,
  patient_id bigint NOT NULL,
  waiting_queue_id bigint,
  appointment_id bigint,
  message text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT workflow_notifications_pkey PRIMARY KEY (id)
);