-- Migration pour ajouter la table notifications_realtime manquante
-- Cette table est référencée dans le code mais n'existe pas dans la base
 
-- ===== CRÉATION DE LA TABLE NOTIFICATIONS TEMPS RÉEL =====

CREATE TABLE IF NOT EXISTS public.notifications_realtime (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type_notification character varying NOT NULL CHECK (type_notification IN ('patient_arrive', 'medecin_disponible', 'consultation_terminee', 'document_scanne', 'urgence', 'rappel', 'patient_called', 'patient_entered', 'patient_status_change')),
  titre character varying NOT NULL,
  message text NOT NULL,
  data jsonb,
  priorite character varying DEFAULT 'normale' CHECK (priorite IN ('basse', 'normale', 'haute', 'urgente')),
  lu boolean DEFAULT false,
  lu_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone
);

-- ===== INDEX POUR OPTIMISER LES PERFORMANCES =====

CREATE INDEX IF NOT EXISTS idx_notifications_realtime_user_id ON public.notifications_realtime(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_lu ON public.notifications_realtime(lu);
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_type ON public.notifications_realtime(type_notification);
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_created_at ON public.notifications_realtime(created_at);

-- ===== POLITIQUES DE SÉCURITÉ ROW LEVEL SECURITY =====

ALTER TABLE public.notifications_realtime ENABLE ROW LEVEL SECURITY;

-- Les utilisateurs peuvent voir leurs propres notifications
CREATE POLICY "Users can view their own realtime notifications" ON public.notifications_realtime
  FOR SELECT USING (auth.uid()::text = user_id::text);

-- Les utilisateurs peuvent mettre à jour leurs propres notifications
CREATE POLICY "Users can update their own realtime notifications" ON public.notifications_realtime
  FOR UPDATE USING (auth.uid()::text = user_id::text);

-- Les utilisateurs peuvent insérer des notifications pour eux-mêmes
CREATE POLICY "Users can insert their own realtime notifications" ON public.notifications_realtime
  FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

-- ===== COMMENTAIRES =====

COMMENT ON TABLE public.notifications_realtime IS 'Notifications temps réel pour les événements critiques du cabinet';
COMMENT ON COLUMN public.notifications_realtime.user_id IS 'ID de l''utilisateur destinataire de la notification';
COMMENT ON COLUMN public.notifications_realtime.type_notification IS 'Type de notification (patient_arrive, medecin_disponible, etc.)';
COMMENT ON COLUMN public.notifications_realtime.data IS 'Données supplémentaires au format JSON';
COMMENT ON COLUMN public.notifications_realtime.priorite IS 'Priorité de la notification (basse, normale, haute, urgente)';
COMMENT ON COLUMN public.notifications_realtime.lu IS 'Indique si la notification a été lue';
COMMENT ON COLUMN public.notifications_realtime.expires_at IS 'Date d''expiration de la notification';
