-- Migration Phase 3 - Module Rendez-vous (Fonctionnalités avancées)
-- Date: 2025-01-02
-- Objectif: Fonctionnalités avancées sans SMS (notifications temps réel, scan documents, optimisations)

-- ===== AMÉLIORATION DES NOTIFICATIONS TEMPS RÉEL =====

-- Ajout de colonnes pour les notifications avancées
ALTER TABLE public.notifications 
ADD COLUMN IF NOT EXISTS priorite character varying DEFAULT 'normale' CHECK (priorite IN ('basse', 'normale', 'haute', 'urgente')),
ADD COLUMN IF NOT EXISTS categorie character varying DEFAULT 'systeme' CHECK (categorie IN ('systeme', 'patient', 'medecin', 'secretaire', 'urgence')),
ADD COLUMN IF NOT EXISTS action_requise boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS action_url character varying,
ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;

-- ===== AMÉLIORATION DU SCAN DE DOCUMENTS =====

-- Ajout de colonnes pour le scan avancé
ALTER TABLE public.documents_patients 
ADD COLUMN IF NOT EXISTS hash_fichier character varying,
ADD COLUMN IF NOT EXISTS version integer DEFAULT 1,
ADD COLUMN IF NOT EXISTS statut_validation character varying DEFAULT 'en_attente' CHECK (statut_validation IN ('en_attente', 'valide', 'rejete', 'archive')),
ADD COLUMN IF NOT EXISTS valide_par bigint REFERENCES public.users(id),
ADD COLUMN IF NOT EXISTS date_validation timestamp with time zone,
ADD COLUMN IF NOT EXISTS tags text[],
ADD COLUMN IF NOT EXISTS metadata jsonb;

-- ===== NOUVELLE TABLE POUR LES NOTIFICATIONS TEMPS RÉEL =====

CREATE TABLE IF NOT EXISTS public.notifications_realtime (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  type_notification character varying NOT NULL CHECK (type_notification IN ('patient_arrive', 'medecin_disponible', 'consultation_terminee', 'document_scanne', 'urgence', 'rappel')),
  titre character varying NOT NULL,
  message text NOT NULL,
  data jsonb,
  priorite character varying DEFAULT 'normale',
  lu boolean DEFAULT false,
  lu_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone
);

-- ===== NOUVELLE TABLE POUR LES SESSIONS DE SCAN =====

CREATE TABLE IF NOT EXISTS public.sessions_scan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id bigint NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  medecin_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
  secretaire_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date_session timestamp with time zone DEFAULT now(),
  statut character varying DEFAULT 'en_cours' CHECK (statut IN ('en_cours', 'terminee', 'annulee')),
  nombre_documents integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- ===== AMÉLIORATION DE LA SALLE D'ATTENTE =====

-- Ajout de colonnes pour la gestion avancée de la salle d'attente
ALTER TABLE public.waiting_queue 
ADD COLUMN IF NOT EXISTS temps_attente_estime interval,
ADD COLUMN IF NOT EXISTS priorite_medicale character varying DEFAULT 'normale' CHECK (priorite_medicale IN ('normale', 'urgente', 'tres_urgente')),
ADD COLUMN IF NOT EXISTS motif_urgence text,
ADD COLUMN IF NOT EXISTS documents_en_attente boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS notification_envoyee boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS derniere_notification timestamp with time zone;

-- ===== NOUVELLE TABLE POUR LES STATISTIQUES TEMPS RÉEL =====

CREATE TABLE IF NOT EXISTS public.statistiques_realtime (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_statistique date NOT NULL,
  medecin_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
  nombre_patients_vus integer DEFAULT 0,
  temps_moyen_consultation interval,
  nombre_urgences integer DEFAULT 0,
  nombre_documents_scannes integer DEFAULT 0,
  temps_attente_moyen interval,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(date_statistique, medecin_id)
);

-- ===== INDEX POUR OPTIMISER LES PERFORMANCES =====

-- Index pour les notifications temps réel
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_user_id ON public.notifications_realtime(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_lu ON public.notifications_realtime(lu);
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_type ON public.notifications_realtime(type_notification);
CREATE INDEX IF NOT EXISTS idx_notifications_realtime_created_at ON public.notifications_realtime(created_at);

-- Index pour les sessions de scan
CREATE INDEX IF NOT EXISTS idx_sessions_scan_patient_id ON public.sessions_scan(patient_id);
CREATE INDEX IF NOT EXISTS idx_sessions_scan_medecin_id ON public.sessions_scan(medecin_id);
CREATE INDEX IF NOT EXISTS idx_sessions_scan_date_session ON public.sessions_scan(date_session);

-- Index pour les statistiques temps réel
CREATE INDEX IF NOT EXISTS idx_statistiques_realtime_date ON public.statistiques_realtime(date_statistique);
CREATE INDEX IF NOT EXISTS idx_statistiques_realtime_medecin ON public.statistiques_realtime(medecin_id);

-- Index pour les améliorations de la salle d'attente
CREATE INDEX IF NOT EXISTS idx_waiting_queue_priorite_medicale ON public.waiting_queue(priorite_medicale);
CREATE INDEX IF NOT EXISTS idx_waiting_queue_documents_en_attente ON public.waiting_queue(documents_en_attente);
CREATE INDEX IF NOT EXISTS idx_waiting_queue_notification_envoyee ON public.waiting_queue(notification_envoyee);

-- Index pour les documents patients améliorés
CREATE INDEX IF NOT EXISTS idx_documents_patients_statut_validation ON public.documents_patients(statut_validation);
CREATE INDEX IF NOT EXISTS idx_documents_patients_valide_par ON public.documents_patients(valide_par);
CREATE INDEX IF NOT EXISTS idx_documents_patients_tags ON public.documents_patients USING GIN(tags);

-- ===== FONCTIONS AVANCÉES =====

-- Fonction pour calculer le temps d'attente estimé
CREATE OR REPLACE FUNCTION calculer_temps_attente_estime()
RETURNS TRIGGER AS $$
DECLARE
    position_actuelle integer;
    temps_consultation_moyen interval;
    temps_attente interval;
BEGIN
    -- Récupérer la position actuelle dans la file
    SELECT order_position INTO position_actuelle 
    FROM public.waiting_queue 
    WHERE id = NEW.id;
    
    -- Récupérer le temps de consultation moyen du médecin
    SELECT (duree_consultation || ' minutes')::interval INTO temps_consultation_moyen
    FROM public.users 
    WHERE id = NEW.medecin_id;
    
    -- Calculer le temps d'attente estimé
    temps_attente = (position_actuelle - 1) * temps_consultation_moyen;
    
    NEW.temps_attente_estime = temps_attente;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger pour calculer le temps d'attente estimé
CREATE TRIGGER trigger_calculer_temps_attente_estime 
    BEFORE INSERT OR UPDATE ON public.waiting_queue 
    FOR EACH ROW EXECUTE FUNCTION calculer_temps_attente_estime();

-- Fonction pour créer une notification temps réel
CREATE OR REPLACE FUNCTION creer_notification_realtime(
    p_user_id bigint,
    p_type character varying,
    p_titre character varying,
    p_message text,
    p_data jsonb DEFAULT NULL,
    p_priorite character varying DEFAULT 'normale'
)
RETURNS bigint AS $$
DECLARE
    notification_id bigint;
BEGIN
    INSERT INTO public.notifications_realtime (
        user_id, type_notification, titre, message, data, priorite
    ) VALUES (
        p_user_id, p_type, p_titre, p_message, p_data, p_priorite
    ) RETURNING id INTO notification_id;
    
    RETURN notification_id;
END;
$$ language 'plpgsql';

-- Fonction pour notifier l'arrivée d'un patient (version améliorée)
CREATE OR REPLACE FUNCTION notifier_arrivee_patient_avancee()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'present' AND OLD.status != 'present' THEN
        -- Notifier le médecin
        PERFORM creer_notification_realtime(
            NEW.medecin_id,
            'patient_arrive',
            'Patient arrivé',
            'Le patient ' || (SELECT prenom || ' ' || nom FROM public.patients WHERE id = NEW.patient_id) || ' est arrivé en salle d''attente',
            jsonb_build_object(
                'patient_id', NEW.patient_id, 
                'waiting_queue_id', NEW.id,
                'temps_attente_estime', NEW.temps_attente_estime
            ),
            'normale'
        );
        
        -- Marquer que la notification a été envoyée
        NEW.notification_envoyee = true;
        NEW.derniere_notification = now();
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Remplacer l'ancien trigger par le nouveau
DROP TRIGGER IF EXISTS trigger_notifier_arrivee_patient ON public.waiting_queue;
CREATE TRIGGER trigger_notifier_arrivee_patient_avancee 
    AFTER UPDATE ON public.waiting_queue 
    FOR EACH ROW EXECUTE FUNCTION notifier_arrivee_patient_avancee();

-- Fonction pour notifier le scan de documents
CREATE OR REPLACE FUNCTION notifier_scan_document()
RETURNS TRIGGER AS $$
BEGIN
    -- Notifier le médecin que des documents ont été scannés
    PERFORM creer_notification_realtime(
        (SELECT medecin_id FROM public.sessions_scan WHERE id = NEW.id),
        'document_scanne',
        'Document scanné',
        'Nouveau document scanné pour le patient ' || (SELECT prenom || ' ' || nom FROM public.patients WHERE id = NEW.patient_id),
        jsonb_build_object(
            'patient_id', NEW.patient_id,
            'document_id', NEW.id,
            'type_document', NEW.type_document,
            'nom_fichier', NEW.nom_fichier
        ),
        'normale'
    );
    
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger pour notifier le scan de documents
CREATE TRIGGER trigger_notifier_scan_document 
    AFTER INSERT ON public.documents_patients 
    FOR EACH ROW EXECUTE FUNCTION notifier_scan_document();

-- Fonction pour mettre à jour les statistiques temps réel
CREATE OR REPLACE FUNCTION mettre_a_jour_statistiques_realtime()
RETURNS TRIGGER AS $$
DECLARE
    date_aujourd_hui date := CURRENT_DATE;
    stat_id bigint;
BEGIN
    -- Vérifier si une statistique existe pour aujourd'hui et ce médecin
    SELECT id INTO stat_id 
    FROM public.statistiques_realtime 
    WHERE date_statistique = date_aujourd_hui AND medecin_id = NEW.medecin_id;
    
    IF stat_id IS NULL THEN
        -- Créer une nouvelle entrée de statistiques
        INSERT INTO public.statistiques_realtime (
            date_statistique, medecin_id, nombre_patients_vus
        ) VALUES (
            date_aujourd_hui, NEW.medecin_id, 1
        );
    ELSE
        -- Mettre à jour les statistiques existantes
        UPDATE public.statistiques_realtime 
        SET 
            nombre_patients_vus = nombre_patients_vus + 1,
            updated_at = now()
        WHERE id = stat_id;
    END IF;
    
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger pour mettre à jour les statistiques quand une consultation se termine
CREATE TRIGGER trigger_mettre_a_jour_statistiques 
    AFTER UPDATE ON public.consultations 
    FOR EACH ROW 
    WHEN (NEW.statut = 'terminee' AND OLD.statut != 'terminee')
    EXECUTE FUNCTION mettre_a_jour_statistiques_realtime();

-- ===== TRIGGERS POUR LES COLONNES D'AUDIT =====

-- Trigger pour les sessions de scan
CREATE TRIGGER update_sessions_scan_updated_at 
    BEFORE UPDATE ON public.sessions_scan 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Trigger pour les statistiques temps réel
CREATE TRIGGER update_statistiques_realtime_updated_at 
    BEFORE UPDATE ON public.statistiques_realtime 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ===== DONNÉES DE TEST POUR LES NOUVELLES FONCTIONNALITÉS =====

-- Insérer quelques sessions de scan de test
INSERT INTO public.sessions_scan (patient_id, medecin_id, secretaire_id, statut, nombre_documents)
SELECT 
    p.id,
    u.id,
    (SELECT id FROM public.users WHERE role = 'secretary' LIMIT 1),
    'terminee',
    2
FROM public.patients p, public.users u 
WHERE u.role = 'doctor' 
LIMIT 3
ON CONFLICT DO NOTHING;

-- Insérer quelques statistiques de test
INSERT INTO public.statistiques_realtime (date_statistique, medecin_id, nombre_patients_vus, temps_moyen_consultation, nombre_urgences)
SELECT 
    CURRENT_DATE,
    u.id,
    5,
    '30 minutes'::interval,
    1
FROM public.users u 
WHERE u.role = 'doctor'
ON CONFLICT (date_statistique, medecin_id) DO NOTHING;

-- ===== POLITIQUES RLS POUR LES NOUVELLES TABLES =====

-- Activer RLS sur les nouvelles tables
ALTER TABLE public.notifications_realtime ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions_scan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistiques_realtime ENABLE ROW LEVEL SECURITY;

-- Politiques pour les notifications temps réel
CREATE POLICY "Users can view their own realtime notifications" ON public.notifications_realtime
  FOR SELECT USING (auth.uid()::bigint = user_id);

CREATE POLICY "Users can update their own realtime notifications" ON public.notifications_realtime
  FOR UPDATE USING (auth.uid()::bigint = user_id);

-- Politiques pour les sessions de scan
CREATE POLICY "Users can view scan sessions" ON public.sessions_scan
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can create scan sessions" ON public.sessions_scan
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update scan sessions" ON public.sessions_scan
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Politiques pour les statistiques temps réel
CREATE POLICY "Users can view realtime statistics" ON public.statistiques_realtime
  FOR SELECT USING (auth.role() = 'authenticated');

-- ===== COMMENTAIRES ET DOCUMENTATION =====

COMMENT ON TABLE public.notifications_realtime IS 'Notifications temps réel pour les événements critiques du cabinet';
COMMENT ON TABLE public.sessions_scan IS 'Sessions de scan de documents pour les patients';
COMMENT ON TABLE public.statistiques_realtime IS 'Statistiques temps réel pour le suivi des performances';

COMMENT ON COLUMN public.notifications_realtime.priorite IS 'Priorité de la notification (basse, normale, haute, urgente)';
COMMENT ON COLUMN public.sessions_scan.nombre_documents IS 'Nombre de documents scannés dans cette session';
COMMENT ON COLUMN public.statistiques_realtime.temps_attente_moyen IS 'Temps d''attente moyen des patients pour ce médecin';
